#!/usr/bin/env python3
"""Generate docs/REGISTRY.md and docs/INDEX.md from frontmatter (P2-01)."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"


def grab(text: str, key: str) -> str:
    m = re.search(rf"^{key}:\s*(.+)$", text, re.M)
    return m.group(1).strip() if m else ""


def main() -> None:
    files = sorted(DOCS.rglob("*.md"))
    # INDEX
    rels = [p.relative_to(DOCS).as_posix() for p in files]
    index = [
        "---",
        "id: DOC-0002",
        "title: Documentation Index",
        "status: reviewed",
        "version: 1.0",
        "phase: 0",
        "---",
        "",
        "# INDEX",
        "",
        f"**Count:** {len(rels)}",
        "",
        "## Paths",
        "",
    ] + [f"- `{r}`" for r in rels]
    (DOCS / "INDEX.md").write_text("\n".join(index) + "\n", encoding="utf-8")

    rows = []
    for p in files:
        t = p.read_text(encoding="utf-8", errors="replace")
        rows.append((p.as_posix(), grab(t, "id") or "MISSING", grab(t, "title") or p.stem, grab(t, "status") or "?"))

    reg = [
        "---",
        "id: DOC-0003",
        "title: Registry",
        "status: reviewed",
        "version: 1.2",
        "phase: 0",
        "---",
        "",
        "# Registry (generated by tools/sync_registry.py)",
        "",
        f"**Files:** {len(rows)}",
        "",
        "Do not hand-edit the table; re-run `python tools/sync_registry.py`.",
        "",
        "| ID | Status | Title | Path |",
        "|----|--------|-------|------|",
    ]
    for path, i, title, st in rows:
        reg.append(f"| `{i}` | {st} | {title.replace('|', '/')} | `{path}` |")
    (DOCS / "REGISTRY.md").write_text("\n".join(reg) + "\n", encoding="utf-8")
    print(f"Wrote INDEX ({len(rels)}) and REGISTRY ({len(rows)})")


if __name__ == "__main__":
    main()
